services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - '443:443'       # Expose HTTPS on host
    depends_on:
      - wordpress       # Depends on WordPress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - '9000:9000'     # PHP-FPM exposed for NGINX
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    tty: true
    stdin_open: true
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: always

  adminer:
      container_name: adminer
      build: ./requirements/adminer
      depends_on:
        - mariadb       # Depends on Mariadb and Nginx
      networks:
        - inception
      volumes:
        - wordpress_data:/var/www/html
      restart: always

  redis:
      container_name: redis
      build: ./requirements/redis
      depends_on:
        - wordpress       # Depends on wordpress
      networks:
        - inception
      restart: always

  mysite:
    container_name: mysite
    build: ./requirements/myWebSite
    networks:
        - inception
    ports:
      - '3000:3000'
    restart: always
  
  
  portainer :
    container_name : portainer
    build : ./requirements/portainer
    ports :
      - '9443:9443'
      - '9001:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception

  ftp-server:
    container_name : ftp-server
    build : ./requirements/FTPserver
    depends_on:
      - wordpress
    networks:
      - inception
    ports: 
      - '21:21' 
    volumes :
      -  wordpress_data:/var/www/wordpress
    restart : always


volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/portainer
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge
